### ISSUE TITLE
Relationship to cdk8s?

### ISSUE THREAD

**Issue by ThomasK33** [laurci/kubernate#4]
Hey,

looks like you have recreated [cdk8s](https://github.com/cdk8s-team/cdk8s).

**Comment by laurci** [comment]
It seems like cdk8s and Kubernate have a lot of stuff in common. The same core idea is in place, which actually makes me feel like Kubernate has a really good backing idea. However, Kubernate will never enforce a paradigm or a programming model, you can bring your own. Kubernate also has different visions regarding the inputs and the outputs of your program (please check https://kubernate.dev/inputs.html and https://kubernate.dev/output.html). We also have a lot of features coming to allow user programs to extend the CLI with custom commands and behavior, to get outputs from other infra-as code tools, and use them in your program (Pulumi is wip, terraform coming soon), and new helper resources to help you develop deployments faster.

If you are interested in talking about this, you could join our Discord server (https://discord.gg/fXFMqjzmkY). I would be really interested in talking with you about this :)

Thanks! I will close this issue. If you have anything to add, feel free to re-open it.
